name: joymodels_desktop
description: "JoyModels Desktop Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5+1

  # HTTP Client
  http: ^1.6.0

  # Dependency Injection
  get_it: ^9.2.0

  # Secure Storage
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
